### ISSUE TITLE
Wrong repository/mirror URLs due to unsupported fact 'os_maj_version'

### ISSUE THREAD

**Issue by Flauschbaellchen** [stahnma/puppet-module-puppetlabs_yum#10]
After installing I get:

````
http://yum.puppetlabs.com/el//dependencies/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
http://yum.puppetlabs.com/el//products/x86_64/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "The requested URL returned error: 404 Not Found"
Trying other mirror.
````

System: Centos 6.5
Puppet (Agent): puppet-2.7.25-2.el6.noarch

Bug: The fact ``os_maj_version`` was not yet supported
Fix: Fallback to the fact ``operatingsystemrelease`` or ``lsbdistrelease`` (both '6.5' on my system)

**Comment by stahnma** [comment]
os_maj_version is supported in any facter that is still supported upstream. 

Puppet 2 and Facter 1 are both EOL now.
